stateDiagram-v2
    [*] --> Authentication: User Authentication Process
    
    state Authentication {
        [*] --> Signup
        [*] --> Login
        Signup --> AuthContext
        Login --> AuthContext
        AuthContext --> PrivateRoute
    }
    
    state MovieManagement {
        [*] --> Home
        Home --> MovieCard
        MovieCard --> MovieModal
        MovieModal --> VideoPlayer
        Home --> Collections
    }
    
    state DataHandling {
        Firebase --> Authentication
        Firebase --> Collections
        Axios --> Home
        Utils --> Components
    }
    
    state UIComponents {
        Button
        Input
        Toast
    }
    
    state Routing {
        App
        PrivateRoute
    }
    
    Authentication --> MovieManagement
    DataHandling --> MovieManagement
    UIComponents --> MovieManagement
    Routing --> Authentication
    Routing --> MovieManagement